### ISSUE TITLE
build demo error

### ISSUE THREAD

**Issue by xinlon-z** [xinghaochen/Pose-REN#15]
```
-- OpenCV_HEADERS: /usr/local/include/usr/local/include/opencv
-- BLAS_INCLUDE: /usr/local/cuda-10.1/targets/x86_64-linux/include
-- CUDA_INCLUDE_DIRS: /usr/local/cuda-10.1/include
-- CUDA_CUBLAS_LIBRARIES: /usr/lib/x86_64-linux-gnu/libcublas.so
-- PROTOBUF_LIBRARIES: /usr/lib/x86_64-linux-gnu/libprotobuf.so-lpthread
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lxz/Poes/Pose-REN/src/demo/pose-ren-demo-cpp/src/build
[ 33%] Building CXX object CMakeFiles/PoseREN.dir/hand_pose_estimator.cpp.o
[ 66%] Building CXX object CMakeFiles/PoseREN.dir/run_hand_pose.cpp.o
[100%] Linking CXX executable PoseREN
CMakeFiles/PoseREN.dir/hand_pose_estimator.cpp.o：在函数‘HandPoseEstimator::init_model()’中：
hand_pose_estimator.cpp:(.text+0x2de)：对‘caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
hand_pose_estimator.cpp:(.text+0x368)：对‘caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/PoseREN.dir/build.make:160: recipe for target 'PoseREN' failed
make[2]: *** [PoseREN] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/PoseREN.dir/all' failed
make[1]: *** [CMakeFiles/PoseREN.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by xinghaochen** [comment]
Hi, which caffe did you use? It seems the error somehow comes from the definition of `CopyTrainedLayersFrom`, which should be a standard API for caffe.

**Comment by xinlon-z** [comment]
> Hi, which caffe did you use? It seems the error somehow comes from the definition of `CopyTrainedLayersFrom`, which should be a standard API for caffe.

Hi,I've solved the problem by using  the official version of caffe. I meet this problem when i use the `caffe-pose`.

**Comment by xinlon-z** [comment]
I can only use the python layer. The c++ layer can't work, although it compilation successful.

**Comment by xinghaochen** [comment]
The `caffe-pose` repo is built upon an old branch of official caffe. You can try to merge the updates of caffe into `caffe-pose`.

And what is the specific problem of using c++ layer?
